plugins {
    id 'com.android.application'
}

android {
    namespace 'app.livraisons.hercules'
    compileSdk 36

    defaultConfig {
        applicationId "app.livraisons.hercules"
        minSdk 23
        targetSdk 36
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}
