name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Télécharger le projet
        uses: actions/checkout@v4

      - name: Installer Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Autoriser Gradle
        working-directory: livraisonFactureandroid
        run: chmod +x gradlew

      - name: Compiler l'APK
        working-directory: livraisonFactureandroid
        run: ./gradlew assembleDebug

      - name: Rechercher l'APK
        run: find . -type f -name "*.apk"

      - name: Enregistrer l'APK
        uses: actions/upload-artifact@v4
        with:
          name: application-debug
          path: "**/build/outputs/apk/**/*.apk"
          if-no-files-found: error
